---
title: "Milestone2"
author: "Trevor Cobb"
date: "2/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Project 1: https://andres-deloera.shinyapps.io/ACO_Exploration/
  
  Pros:  
  - Wonderful problem framing and introductory visualizations that pull the viewer into the story in a compelling way. 
  - I like that the insights are shared up front on the opening page. This encourages us to think critically about the data they're presenting.
  - The design is simple but effective
  
  Cons: 
  - Many of the measures on the axis are in "-4e+07" format which means nothing to me
  - Some of the drop downs have too many options, without resulting changes in the visualizations. More focus on quality rather than quantity would be preferrable. 
  

Project 2: https://salomegarnier.shinyapps.io/sex_education_health/
  
  Pros: 
  - Topic is compelling
  - I like that the data tables are provided so we can examine this in raw(ish) format
  - Clear models which are described well and also stand alone. Nice selection and about the right quantity to quality ratio.
  
  Cons:
  - Homepage layout is confusing and non-intuitive
  - Questionable color choices 
  - Much of the work seems to have been done in the wrangling phase: I would have liked to see more analysis and take-aways


